version: '3.9'
services: 
  dev-db:
    image: postgres:15.1
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest
    networks:
      - freddcodecamp
networks:
  freddcodecamp: